### ISSUE TITLE
multiple_app_ports_test in routing suite fails when switching backends is disabled.

### ISSUE THREAD

**Issue by jimconner** [cloudfoundry/cf-acceptance-tests#104]
## Issue

The multiple_app_ports test which was recently added to the 'routing' suite fails when user selection of backends is disabled. 

## Context

For our CF deployments we are deploying only Diego and not deploying DEA/HM9000 components.
As there is only the Diego backend available, we have set `users_can_select_backend: false` in our CF deployment manifest.

The multiple_app_ports test is failing for us as our deployment returns `CF-BackendSelectionNotAuthorized` instead of the expected `CF-MultipleAppPortsMappedDiegoToDea` and this causes the test to fail.

```
• Failure [111.468 seconds]
{NO_DEA_SUPPORT} Multiple App Ports when app has multiple ports mapped [It] returns an error when switching from Diego to DEA 
/var/vcap/packages/acceptance-tests/src/github.com/cloudfoundry/cf-acceptance-tests/routing/multiple_app_ports_test.go:68

  Timed out after 60.000s.
  Expected
      <string>: {
         "code": 320005,
         "description": "You cannot select the backend on which to run this application",
         "error_code": "CF-BackendSelectionNotAuthorized"
      }


  to contain substring
      <string>: CF-MultipleAppPortsMappedDiegoToDea
```

## Steps to Reproduce

Deploy CF with the `users_can_select_backend: false` option set
Run acceptance tests

## Expected result

The test should not have been run as it uses both DEA and Diego backends, but we only have Diego backend deployed, and we have `backed: diego` set in our acceptance test options.

## Current result

Test fails as it receives `CF-BackendSelectionNotAuthorized` instead of the expected `CF-MultipleAppPortsMappedDiegoToDea` result.

## Possible Fix

Check that user selection of backends is allowed, and do not run the test if it is disabled.

**Comment by Amit-PivotalLabs** [comment]
Thanks for catching this @jimconner, I'll let the Routing team know about this /cc @shalako @crhino

**Comment by crhino** [comment]
We decided to remove this specific test from CATs since it is only validating an error case and is sufficiently covered by unit tests.

**Comment by jimconner** [comment]
Thanks @crhino - sounds like a good solution to me.
