### ISSUE TITLE
cf-acceptance-tests - crashing_test.go

### ISSUE THREAD

**Issue by Wayne-H-Ha** [cloudfoundry/cf-acceptance-tests#105]
## Issue

Found the following in the test for cf push -c /bin/false:
```
Eventually(cf.Cf("app", appName), DEFAULT_TIMEOUT).Should(Say("crashed"))
```
## Context

Found the following in the output of the test:
```
     state      since                    cpu    memory   disk     details
#0   crashing   2016-04-26 11:06:10 PM   0.0%   0 of 0   0 of 0
```
## Steps to Reproduce

Should it be expecting crash or crashing instead of crashed?

## Expected result

Expect the test to be flagged as successful.

## Current result

The start of the application returns state of crashing which is expected.  The test is flagged as failure which is not expected.

## Possible Fix

[not obligatory, but suggest fixes or reasons for the bug]

## `name of issue` screenshot

[if relevant, include a screenshot]

**Comment by robdimsdale** [comment]
@Wayne-H-Ha based on the conversation in #106, are you trying to run this test against DEAs? This test should only be run against diego, and is currently passing in our continuous integration against a diego backend.

Rob & @dsabeti

**Comment by Wayne-H-Ha** [comment]
I just confirmed that we are calling test_default and passing 2 parameters to it:

$ grep test_default consoleText.356
  inflating: releases/cf-release/src/github.com/cloudfoundry/cf-acceptance-tests/bin/test_default
  inflating: releases/cf-release/src/github.com/cloudfoundry/cf-acceptance-tests/bin/diego_test_default
+ bin/test_default -skip=SSO -v

If you say this test should not be executed as part of test_default then I will just ignore its result for now.

**Comment by dsabeti** [comment]
@Wayne-H-Ha I think the problem might be that you're passing a second `-skip` flag, which is overriding the first `-skip` flag that disables the `NO_DEA_SUPPORT` skipping. As it turns out, the SSO tests that you want to skip will already be excluded by the `test_default` script: notice that it only runs `apps detect internet_dependent security_groups routing`.

If you remove your `-skip` flag, is the test prevented from running?

**Comment by Wayne-H-Ha** [comment]
Thanks for recommending removing the -skip flag.  Now we get all tests pass:

SUCCESS! 41 Passed 0 Failed 0 Pending 3 Skipped PASS
