### ISSUE TITLE
loggregator endpoint not correctly detected in v3 test suite.

### ISSUE THREAD

**Issue by jimconner** [cloudfoundry/cf-acceptance-tests#110]
## Issue

The loggregator endpoint is not being correctly detected in the v3 test suite. In our deployment we have disabled http API access (https only), and we have loggregator configured with a wss://loggregator.somedomain URL.

In helpers/v3_helpers/v3.go it seems that the loggregator endpoint is chosen by string replacing the name of the ApiEndpoint from api.somedomain to loggregator.somedomain

I think the offending line is line 165 of helpers/v3_helprs/v3.go
`loggregatorEndpoint := strings.Replace(config.ApiEndpoint, "api", "loggregator", -1)`

This does not correctly select the loggregator endpoint in our environment due to the use of websockets and https, and as such the v3 test suite fails.

## Context

API access is https only
traffic_controller_url is set to wss://doppler.somedomain
Loggregator is configured for websockets with a wss://loggregator.somedomain URL

## Steps to Reproduce

Disable http access at the load balancer level (We're using AWS ELBs as our load balancers)
Configure properties.acceptance_tests.api with a https:// URL
Configure dopper/loggregator to use Websocket wss:// URLs (again accessed through AWS ELBs)
Run the v3 test suite.

## Expected result

v3 test suite should succeed.

## Current result

Staging of applications fails as the curl step to read from the loggregator endpoint times out when trying to connect.

```
curl -s loggregator.somedomain/recent?app=d05e989a-8097-476a-b9f3-4f317d874495 -H Authorization:  

• Failure in Spec Teardown (AfterEach) [64.201 seconds]
process [AfterEach] terminating an instance /v3/processes/:guid/instances/:index restarts the instance 
/var/vcap/packages/acceptance-tests/src/github.com/cloudfoundry/cf-acceptance-tests/v3/process_test.go:135

  Timed out after 30.000s.
  Expected process to exit.  It did not.
```

## Possible Fix
Use the same `getCfHomeConfig().LoggregatorEndpoint` method which is used in apps/loggregator_test.go

**Comment by Amit-PivotalLabs** [comment]
Hey @jimconner 

I'll ask the CAPI team who's responsible for the v3 API to take a look at this issue.

/cc @utako @SocalNick 

Cheers,
Amit

**Comment by zrob** [comment]
Hey @jimconner 

This test suite is for currently experimental features.  We recommend you just disable them in your environment for now.

We will eventually rewrite these tests to use the cf cli instead of making curl requests, when cli support has been added for the v3 api.  At that time the cli will be able to manage the websocket request.  Until then what we have is sufficient to test the work in our dev pipelines and we don't plan to change that.

Feel free to reopen this if you have other comments.

Thanks,
@zrob & @utako
