### ISSUE TITLE
Loggregator tests frequently failing

### ISSUE THREAD

**Issue by achawki** [cloudfoundry/cf-acceptance-tests#121]
## Issue

[firehose data](https://github.com/cloudfoundry/cf-acceptance-tests/blob/aefda809a7ce30c38116fcfc4b70c63afff7663e/apps/loggregator_test.go#L86) and [shows container metrics](https://github.com/cloudfoundry/cf-acceptance-tests/blob/aefda809a7ce30c38116fcfc4b70c63afff7663e/apps/loggregator_test.go#L105) tests within the `apps` test suite are frequently failing. 

It seems that it is related to the [noaa library](https://github.com/cloudfoundry/noaa) (authorization/reconnection issues, although the user has sufficient rights)

The functionality itself is working.

## Context

cf v237
Doppler endpoint: wss://doppler.domain
Same result with increased timeouts and `master` version of cf-acceptance-tests

## Steps to Reproduce

Happens frequently (also when only these two tests are executed), but not reproducible.

## Expected result

Tests should succeed.

## Current result

```
loggregator firehose data [It] shows logs and metrics 
/var/vcap/packages/acceptance-tests/src/github.com/cloudfoundry/cf-acceptance-tests/apps/loggregator_test.go:103

  Timed out after 10.000s.
  To enable the logging & metrics firehose feature, please ask your CF administrator to add the 'doppler.firehose' scope to your CF admin user.
  When passed a matcher, ReceiveMatcher's channel *must* receive something.
```

```
loggregator firehose data [It] shows container metrics 
/var/vcap/packages/acceptance-tests/src/github.com/cloudfoundry/cf-acceptance-tests/apps/loggregator_test.go:132

  Expected error:
      <*errors.UnauthorizedError | 0xc821675280>: {
          description: "You are not authorized. Error: Invalid authorization",
      }
      Unauthorized error: You are not authorized. Error: Invalid authorization
  not to have occurred

```

## Possible Fix

Is it maybe related to [#18](https://github.com/cloudfoundry/noaa/issues/18) [#14](https://github.com/cloudfoundry/noaa/issues/14)?!

I have seen similar issues with the [firehose-plugin](https://github.com/cloudfoundry/firehose-plugin), which is also using the `noaa` library. `Error: Invalid authorization` although the token is still valid.

**Comment by Amit-PivotalLabs** [comment]
@wfernandes, can you or someone on your team take a look?

**Comment by Jim-Campbell** [comment]
[The story](https://www.pivotaltracker.com/story/show/121848173) to work on this is now in the Loggregator icebox.

**Comment by wfernandes** [comment]
@Amit-PivotalLabs I'm leaning towards closing this issue since we haven't heard much regarding CATs failures since the upgrade of noaa and we haven't see the CATs fail in any of our environments with respect to the issue mentioned above.

**Comment by Amit-PivotalLabs** [comment]
I didn't report this issue originally, @achawki did.  Might want to check with them if they're still seeing it or still have open questions.

**Comment by achawki** [comment]
@Amit-PivotalLabs @wfernandes we are going to re-enable these two tests with the cf version containing the noaa upgrade. Thanks.
