### ISSUE TITLE
Test pollution caused by `CATS-persistent-app`

### ISSUE THREAD

**Issue by georgethebeatle** [cloudfoundry/cf-acceptance-tests#129]
We @ the garden team are running CATS in the very end of our pipeline and have been facing the following problem: The test in `apps/one_push_many_restarts_test.go` seems to be starting a `CATS-persistent-app` and keeping it running. It only starts it the first time you run the tests only if it is not already there. What we observed is that if for some reason the app goes to `down` or `crashed` state then the test fails:

```
[Fail] An application that's already been pushed [It] can be restarted and still come up 
/tmp/build/357ec5d1/go/src/github.com/cloudfoundry/cf-acceptance-tests/apps/one_push_many_restarts_test.go:73
```

The problem is that the app is already started, but not accessible. If we manually restart the app it is all fixed. There is already a [check](https://github.com/cloudfoundry/cf-acceptance-tests/blob/master/apps/one_push_many_restarts_test.go#L65) that starts it when it is stopped. Maybe you could add one that does the restart if the app entered some bad state.

**Comment by Amit-PivotalLabs** [comment]
Are you doing a fresh deployment of your CF each time, or do you have a long-running CF that you're continually upgrading and running CATS against?

Why does the persistent app crash?  This is not something we see, that sounds like a failure that should be understood.

**Comment by georgethebeatle** [comment]
We have a cf redeploy in our pipeline before the CATS. I think the app breaks down because sometimes deployment breaks (e.g. some job does not start) and is later recovered. I don't really get why the test is not removing this app in an AfterEach, but I guess it is on purpose, maybe because of its persistent nature.

**Comment by Amit-PivotalLabs** [comment]
Yes, the app is persistent on purpose.  We have fresh-deploy environments and long-lived update environments, and we continually run CATS against both types of environments in the cf-release pipelines.  I haven't seen an issue with the persistent app.  If it's causing problems, there's probably something broken about your platform that needs to be understood.

**Comment by georgethebeatle** [comment]
We will investigate further - this seems to happen regularly on our pipeline.
