### ISSUE TITLE
The ssh suite has implicit tests in a BeforeEach block

### ISSUE THREAD

**Issue by APShirley** [cloudfoundry/cf-acceptance-tests#130]
@ematpl,

All the tests in the ssh suite seem to be implicitly testing the functionality for checking whether you are connecting to the correct container. The [before each block](https://github.com/cloudfoundry/cf-acceptance-tests/blob/master/ssh/ssh_test.go#L37-L58) pushes an app with two instances and then [waits for the correct instance index to be returned](https://github.com/cloudfoundry/cf-acceptance-tests/blob/master/ssh/ssh_test.go#L55-L57). 

This feels to me like it should really be an _explicit_ test of that functionality with an it block that says "it should ssh into the correct container" rather than a test that is _implicit_ in every run of tests on other functionality. The tests then all try to connect to the second instance (index 1 instead of 0), this isn't really testing the instance is the correct one, since it really just relies on the cli correctly constructing the request to connect to some app.

Thanks,
Al

EDIT: creating the issue here since it is relevant to cf-acceptance-tests and not diego, however we should probably move the issue into the diego backlog as your team own the test suite implementation.

**Comment by ematpl** [comment]
Hey, @APShirley, just to make sure, you're proposing that the SSH test suite be restructured as follows (cc @jfmyers9):

- Add an explicit `It` assertion that verifies that on a multi-instance app, `cf ssh -i INDEX` accesses the correct instance each time.
- Change the shared setup for the other SSH tests to create the SSH target app with only one instance and verify other SSH functionality on that single instance.

If so, that change makes sense, and would also reduce the total app-instance load of the entire suite from 16 instances to 10. 👍 The Diego team could prioritize that work.

Thanks,
Eric
