### ISSUE TITLE
Vendoring Path Mismatch

### ISSUE THREAD

**Issue by thomasmmitchell** [cloudfoundry/cf-acceptance-tests#131]
https://github.com/cloudfoundry/cf-acceptance-tests/commit/730bc2a46fd4e7a399ccd5876cb273f74b93eb88
^^
This recent commit changed the import path 
`github.com/cloudfoundry-incubator/cf-routing-test-helpers/schema`
to
`code.cloudfoundry.org/cf-routing-test-helpers/schema`
which is not vendored. Presumably, goimports "helped". This caused vendoring to not work.

**Comment by dsabeti** [comment]
@thomasmmitchell Thanks for the heads up on this. We're fixing it now

**Comment by dsabeti** [comment]
Ok, it should be fixed as of https://github.com/cloudfoundry/cf-acceptance-tests/commit/7ef3edfb8c7edc4e3027f4d9817d6fb4534cf095
