### ISSUE TITLE
security_groups suite - remove assumption of no existing security groups on deployment

### ISSUE THREAD

**Issue by zachgersh** [cloudfoundry/cf-acceptance-tests#134]
Currently, we set a default security group when deploying our CF - this leads to problems as the initial part of the test assumes that the permissions are not wide open and there are no security groups to speak of.

The better approach would be to in a `BeforeEach` to `list` and then `unbind` the security group for staging. `AfterEach` you would then want to `bind` all of the security groups that were previously removed.

Does this sound reasonable?

**Comment by Amit-PivotalLabs** [comment]
Hey @zachgersh 

I don't think it's possible to unbind the default running security groups from a space, and I don't think you have any control whatsoever on the staging security groups.

* https://github.com/cloudfoundry/cloud_controller_ng/blob/126b1c74fc6abd9963f060a41b865301f937226e/lib/cloud_controller/diego/egress_rules.rb#L4-L11
* https://github.com/cloudfoundry/cloud_controller_ng/blob/master/app/models/runtime/space.rb#L30-L34

**Comment by zachgersh** [comment]
@Amit-PivotalLabs - we actually did this security group manipulation to make these tests pass - it is totally possible. 

The CLI has:
`unbind-security-group - Unbind a security group from a space`
`unbind-staging-security-group - Unbind a security group from the set of security groups for staging applications`
`unbind-running-security-group - Unbind a security group from the set of security groups for running applications`

**Comment by Amit-PivotalLabs** [comment]
Globally, not on a per-space basis.

**Comment by Amit-PivotalLabs** [comment]
We'll change this test such that, in a `BeforeEach`, it will assert a pre-condition that the security groups are sufficiently locked down, validating the assumption that the rest of the test depends on.  If they are not locked down, the test should fail fast with a clear failure message using gomega's ability to annotate assertions: https://onsi.github.io/gomega/#annotating-assertions
