### ISSUE TITLE
Please remove DEA specific language

### ISSUE THREAD

**Issue by zachgersh** [cloudfoundry/cf-acceptance-tests#135]
These comments are confusing since no DEA support is required:

https://github.com/cloudfoundry/cf-acceptance-tests/blob/master/security_groups/running_security_groups_test.go#L84-L86

https://github.com/cloudfoundry/cf-acceptance-tests/blob/master/security_groups/running_security_groups_test.go#L69

**Comment by jaresty** [comment]
We fixed the language in this repo.
