### ISSUE TITLE
CATs v3 helpers introduce a Bash dependency

### ISSUE THREAD

**Issue by APShirley** [cloudfoundry/cf-acceptance-tests#138]
CATs run on windows in some cases, where there is no guarantee of having working bash. The [v3 helpers use `grep` to pull in the bearer token](https://github.com/cloudfoundry/cf-acceptance-tests/blob/master/helpers/v3_helpers/v3.go#L101) from UAA. 

According to "sources" (I didn't actually speak to them) on the uaa team, currently only `Bearer` type tokens are issued by this endpoint anyway so we may just be able to stop using `bash -c` and `grep`. If this is not the case, it still may be better to handle the output directly in go code so we can keep CATs OS agnostic.

@utako && @SocalNick what do you think about removing the bash code?

**Comment by SocalNick** [comment]
@APShirley I think `cf oauth-token` returns `bearer <token>`, no need for bash / grep.

**Comment by APShirley** [comment]
[Fixed this](https://github.com/cloudfoundry/cf-acceptance-tests/commit/9984163890c957c091529f1389743b26a8a4ccf4), closing the issue.
