### ISSUE TITLE
config_test.go pollutes the environment of the node it runs on

### ISSUE THREAD

**Issue by mmb** [cloudfoundry/cf-acceptance-tests#141]
Create a new file `helpers/config/another_test.go`:

```
package config_test

import (
	"os"

	. "github.com/onsi/ginkgo"
	. "github.com/onsi/gomega"
)

var _ = Describe("another test", func() {
	It("test", func() {
		Expect(os.Getenv("CONFIG")).To(Equal("test"))
	})
})
```

Run:

```sh
CONFIG=test ginkgo -untilItFails helpers/config/
```

This will eventually fail when the polluting test runs before the test that expects CONFIG to be set to test.

**Comment by Amit-PivotalLabs** [comment]
Thanks @mmb 

We're going to clean up the code a bit, but I suspect this wasn't really the problem you were having, was it?  Why are you running the helper tests in the first place?  Note, you should not be running with `-r` any more, all the CATS are in a single suite at the top level of the repo (that suite pulls in packages in subdirectories, but that's irrelevant).

**Comment by Amit-PivotalLabs** [comment]
This work should now be done.  Closing issue.

**Comment by mmb** [comment]
Thanks @amitkgupta. We have also removed `-r` from all of our pipelines.
