### ISSUE TITLE
droplet bits test cause unexpected error when run in a windows environment

### ISSUE THREAD

**Issue by nickwei84** [cloudfoundry/cf-acceptance-tests#142]
The following line fails: https://github.com/cloudfoundry/cf-acceptance-tests/blob/master/apps/droplet_uploading_and_downloading.go#L62

The test "Users can manage droplet bits for an app" in the `apps/droplet_uploading_and_downloading.go` runs `tar -z` which in a windows environment will fail to uncompress with `gzip`, and cause the ginkgo tests to exist with status code 2.

Instead of invoking `tar -ztf` to extract the file and list the contents, this could be done in two separate steps (ie. first `gzip` then `tar`). This way it would work on both windows and non-windows environments.

**Comment by Amit-PivotalLabs** [comment]
Thanks @nickwei84 

We don't have Windows machines.  Would you be interested in submitting a PR for this, you would be able to try it on your Windows machine and confirm that it works.

**Comment by nickwei84** [comment]
@amitkgupta Sounds good. Will do.

**Comment by Amit-PivotalLabs** [comment]
Thanks.  Closing issue in anticipation of PR.
