### ISSUE TITLE
v3 Tasks Test Makes Assumption that CC Tasks Are Enabled

### ISSUE THREAD

**Issue by zachgersh** [cloudfoundry/cf-acceptance-tests#149]
when running v3 test and using "IncludeTasks" you will run into the issue that Tasks are not enabled by default unless you flip the feature flag for cc.

Referencing these tests:

https://github.com/cloudfoundry/cf-acceptance-tests/blob/master/v3/task.go#L65

Error you are going to get from your test:

```json
{
   "errors": [
      {
         "code": 330002,
         "detail": "Feature Disabled: task_creation",
         "title": "CF-FeatureDisabled"
      }
   ]
}
```

Of course you can then go use `cf enable-feature-flag` to fix this but why wouldn't the test hit the endpoint to enable this by default?

**Comment by dsabeti** [comment]
@zachgersh Yeah, this is unfortunate, but I think there's a good reason for it. 

Imagine that CATs enabled task creation or using docker images (another feature flag with the same approach in CATs). What you now have is a test suite that enables a feature on an actual CF instance. To restate it differently, the tests mutate and reconfigure the platform that they're testing. In some dev environments, that _might_ be fine, but you'd never want to run CATs against a production instance. Even in dev environments, it could lead to confusion as people would wonder when the configuration of their CF instance changed.

Now, I could potentially imagine (yet) another config parameter like `enable_feature_flags` for CATs, that would be false by default but you could set to true, that would notice that the feature flag was disabled and enable it. Still, the person running CATs would have to know to set that field to true before running their tests -- not a whole lot less work than enabling the flag on their own.

Do you have any other thoughts on it?

**Comment by dsabeti** [comment]
Hey @zachgersh, any other thoughts on this? If not, I'd like to close the issue.
