### ISSUE TITLE
Several skip messages don't include notes

### ISSUE THREAD

**Issue by Amit-PivotalLabs** [cloudfoundry/cf-acceptance-tests#164]
At minimum, I noticed when Zipkin and ContainerNetworking are skipped (for example, if I don't mention them at all in my CONFIG since they seem to default to not be included), my CATS output doesn't say why they're being skipped, so I don't know what to do with my platform to enable those tests.  There may be other missing notes as well.

**Comment by dsabeti** [comment]
Thanks for the feedback. I've added these stories below and will try to prioritize them soon. Would you mind closing this issue in the meantime?

https://www.pivotaltracker.com/story/show/135889049
https://www.pivotaltracker.com/story/show/135889081
