### ISSUE TITLE
Alphabetize the example integration_config test suites

### ISSUE THREAD

**Issue by wendorf** [cloudfoundry/cf-acceptance-tests#170]
zipkin should be lower.

**Comment by JesseTAlford** [comment]
Yeah it should. Looks like we'll have to fix it in the struct and test, too. I wonder how it got that way?

**Comment by jaresty** [comment]
This has [been fixed](https://github.com/cloudfoundry/cf-acceptance-tests/commit/ef079a3a59754f64d52d849fe49c9408d10471a4)
