### ISSUE TITLE
Random errors running CAT test on test space cleanup

### ISSUE THREAD

**Issue by amhuber** [cloudfoundry/cf-acceptance-tests#174]
I'm getting random failures running the CAT tests when one of the tests completes and the test org and quota are being deleted.  The error looks like this:

    • Failure in Spec Teardown (AfterEach) [36.868 seconds]
    [apps] Getting instance information
    /root/.gvm/pkgsets/go1.6.2/global/src/github.com/cloudfoundry/cf-acceptance-tests/cats_suite_helpers/cats_suite_helpers.go:38
      scaling memory
      /root/.gvm/pkgsets/go1.6.2/global/src/github.com/cloudfoundry/cf-acceptance-tests/apps/instance_reporting.go:57
        fails with insufficient resources [AfterEach]
        /root/.gvm/pkgsets/go1.6.2/global/src/github.com/cloudfoundry/cf-acceptance-tests/apps/instance_reporting.go:56
    
        No future change is possible.  Bailing out early after 5.288s.
        Expected
            <int>: 1
        to match exit code:
            <int>: 0

The output from the CF CLI is as follows:

    [2017-01-10 22:08:14.58 (UTC)]> cf delete-org -f CATS-1-ORG-da6de8f6-24cd-48ca-4
    Deleting org CATS-1-ORG-da6de8f6-24cd-48ca-4 as admin...
    OK
    
    [2017-01-10 22:08:14.79 (UTC)]> cf delete-quota -f CATS-1-QUOTA-98f68f49-11a8-4f8f-7
    Deleting quota CATS-1-QUOTA-98f68f49-11a8-4f8f-7 as admin...
    FAILED
    Please delete the organization associations for your quota definition.

The best I can tell is that the CC hasn't finished processing the org deletion to free up the association to the quota, so when the quota delete command is run (only two tenths of a second later).  The CC throws an error.  I'm always able to delete the quota after the test has failed so it certainly seems to be a timing issue.

Perhaps just adding a short sleep in between the commands would resolve the issue?  Here is the relevant code:

https://github.com/cloudfoundry-incubator/cf-test-helpers/blob/master/workflowhelpers/internal/space.go#L113-L119

**Comment by dsabeti** [comment]
Hi @amhuber. What version of the CLI are you using? There's been a regression in the cf CLI so that it doesn't wait for deletion operations to complete before exiting. The regression was introduced in v6.23. If that's the version you're using, you can just downgrade to v6.22.2 and everything should be fine.

**Comment by amhuber** [comment]
Yes, I am using v6.23 so that probably explains it.  I'll downgrade and re-test and close the issue if the test runs cleanly.

**Comment by amhuber** [comment]
That fixed it, thanks!  Closing the issue.
