### ISSUE TITLE
Example config in README should match config defaults

### ISSUE THREAD

**Issue by ljfranklin** [cloudfoundry/cf-acceptance-tests#196]
Hi RelInt team!

On CAPI team, we often ask PR submitters to successfully run CATs before submitting the PR. However, they often admit that they were unable to get all the CATs to pass against a bosh-lite. This isn't unexpected as may of the suites require special setup to pass like `include_backend_compatibility`. It seems like it would be helpful for the config shown in the [README](https://github.com/cloudfoundry/cf-acceptance-tests#test-configuration) to only run the default core suites that would pass on any environment. So something like:

```json
{
  "api": "api.bosh-lite.com",
  "apps_domain": "bosh-lite.com",
  "admin_user": "admin",
  "admin_password": "admin",
  "skip_ssl_validation": true
}
```

Any thoughts on making this change?

**Comment by dsabeti** [comment]
Hey @ljfranklin. I just updated the README so its example config should pass a standard deployment. It turns off all the suites that require some sort of special configuration. I decided be explicit and continue naming all the suites. Take a look and let me know what you think.

**Comment by ljfranklin** [comment]
Works for me, thanks!
