### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by nickwei84** [cloudfoundry/cf-acceptance-tests#226]
We suggest adding the `-f` flag to the following script in the README for non-interactive functionality. This will avoid an interactive prompt in automation use cases.

Current:
`Install the cf-networking plugin for the cf cli: cf install-plugin -r CF-Community "network-policy"`
Suggestion:
`Install the cf-networking plugin for the cf cli: cf install-plugin -f -r CF-Community "network-policy"`

**Comment by dsabeti** [comment]
Hey @nickwei84, how's this: https://github.com/cloudfoundry/cf-acceptance-tests/commit/62c6bfffe2df844706b91e67699c1d368c7f99f8?

**Comment by dsabeti** [comment]
Closing the issue. I've updated the README with @nickwei84 's feedback.
