### ISSUE TITLE
V3 api calls are made when ignore_v3 is set to true

### ISSUE THREAD

**Issue by sharms** [cloudfoundry/cf-acceptance-tests#232]
When tests are configured to ignore_v3, /v3 api calls are still made, such as DeleteApp: https://github.com/cloudfoundry/cf-acceptance-tests/blob/0ff8a97ff02dad4e68b7172bfad27edb2ccef894/helpers/v3_helpers/v3.go#L157

**Comment by dsabeti** [comment]
Hey @sharms. 

I'm assuming you mean [the `include_v3` flag](https://github.com/cloudfoundry/cf-acceptance-tests/blame/master/README.md#L142). That flag opts you in/out of running [the v3 _tests_](https://github.com/cloudfoundry/cf-acceptance-tests/tree/master/v3), not all v3 API calls.

Is there a problem being caused when the test suite makes v3 API calls?

**Comment by dsabeti** [comment]
Hi @sharms, I'm going to close this issue due to inactivity, but feel free to reopen it if you have more questions.
