### ISSUE TITLE
limited service access to cats

### ISSUE THREAD

**Issue by eugenetolan** [cloudfoundry/cf-acceptance-tests#240]
We have a service that has been limited down to only be used by designed orgs. When our CATS run they create a new Org every time they run, this is then resulting in the service plan not being available to that new org. Is there any way to do this without having a persistent Org/App?

**Comment by dsabeti** [comment]
Hey @eugenetolan. Could you show me the config.json **with passwords removed**? IIRC, CATs creates a new service broker for each of its services tests, so I'm not sure how your org-scoped service is affecting the test suite?

Also, I'm curious about how and why you're running CATs. Is it part of a CI test suite? Do you run it after deploying?

**Comment by eugenetolan** [comment]
@dsabeti 
{
  "api": "api.xxxxxxxxxxx",
  "apps_domain": "cf.xxxxxxxxxxxxxx",
  "client_cert_auth_apps_domain": "cfcc.xxxxxxxxxxxxxxxxx",
  "admin_user": "xxxxxxxxxx",
  "admin_password": "xxxxxxxxxxxxxxxxx",
  "skip_ssl_validation": false,
  "backend": "dea",
  "use_http": false,
  "include_apps": true,
  "include_nimbus": true,
  "include_backend_compatibility": false,
  "include_container_networking": false,
  "include_detect": true,
  "include_docker": true,
  "include_internet_dependent": true,
  "include_private_docker_registry": false,
  "include_privileged_container_support": false,
  "include_route_services": false,
  "include_routing": false,
  "include_security_groups": false,
  "include_services": false,
  "include_ssh": true,
  "include_sso": false,
  "include_tasks": false,
  "include_v3": false,
  "include_zipkin": false
}

### include_nimbus is our series of service testings (i.e mongo, redis, vault-ha, mysql, rabbitmq etc, this is where one the issue lies as one of the services is only viewable to one Org)

For our CATs, it doesn't create a new service broker for each test, it simply pushes an application that binds services that are viewable from the marketplace. 

We run CATs every few hours to keep an overall view of the health of our cloudfoundry.

**Comment by dsabeti** [comment]
Ah, I see. You're extending the suite with your own tests for these services.

I should start by saying that I don't think of, and wouldn't recommend, CATs as a monitoring tool for Cloud Foundry deployments, especially if they're production deployments. For that I'd recommend something like [smoke-tests](https://github.com/cloudfoundry/cf-smoke-tests). I recognize that it's really small subset of the coverage that CATs gives, and I'm hoping to dedicate some time to seriously revamping both smoke-tests and CATs soon. It would be really helpful if you could let us know what kind of coverage you'd want it to include, as that input could help guide the kind of changes we need to make. For what it's worth, other ops teams have built various forms of SLIs (Service Level Indicators) for measuring the things they care about most, and I could loop them in to give you some advise.

To address your actual question, in your test (perhaps in a `BeforeEach`), you can run 
```
cf enable-service-access SERVICE -p PLAN -o ORG
```
and you can fetch the org name from
```
TestSetup.RegularUserContext().Org
```

**Comment by eugenetolan** [comment]
@dsabeti Cool,
I will look into the smoke-tests and try to use them instead of acceptance tests. I thought I would have to do the 'enable-service-access' each time.
Thanks for the help!

**Comment by eugenetolan** [comment]
@dsabeti I was able to use TestSetup.RegularUserContext().Org to retrive the Org that CATs is using, though my next issue
