### ISSUE TITLE
skip_ssl_validation not used in sso_helper.go

### ISSUE THREAD

**Issue by trastle** [cloudfoundry/cf-acceptance-tests#25]
Hi All,

I am running the CF171 CATS tests against an install of CF171. The majority of the tests pass however I am seeing an issue in ```sso_lifecycle_test.go```. 

The test shown below uses the helper to curl a URL and expect a ```0``` return code. In the instance shown below it is returning ```60``` because a self signed certificate is in use:

Helper line which is causing the failure:

https://github.com/cloudfoundry/cf-acceptance-tests/blob/master/services/helpers/sso.go#L37

Curl docs detailing the error return code:

    CURLE_SSL_CACERT (60)
    Peer certificate cannot be authenticated with known CA certificates.

When calling the tests I am passing ```"skip_ssl_validation": true```. With this flag set curl should also skip SSL validation or the ```60``` return code should be handled by the helper. 

#### Log from test run:

    [32m> gcf delete d258e916-6761-451d-5ee1-fa87f1290598 -f [0m
    Deleting app d258e916-6761-451d-5ee1-fa87f1290598 in org CATS-ORG-1-2014_06_05-09h53m32.849s / space CATS-SPACE-1-2014_06_05-09h53m32.849s as CATS-USER-1-2014_06_05-09h53m32.849s...
    OK
    [91m[1m• Failure [34.772 seconds][0m
    [90mSSO Lifecycle [0m[91m[1m[BeforeEach] When a service broker is deleted [0m[90mcan no longer perform an operation on a user's behalf using sso [0m
    [37m/var/vcap/store/jenkins_master/workspace/test-cf-cats/cf-release/src/acceptance-tests/services/sso_lifecycle_test.go:107[0m

      [91mExpected
          <int>: 60
      to match exit code:
          <int>: 0[0m

      /var/vcap/store/jenkins_master/workspace/test-cf-cats/gopath/src/github.com/cloudfoundry/cf-acceptance-tests/services/helpers/sso.go:37
    [90m------------------------------[0m
    [32m•[0m
    [1m[91mRan 5 of 5 Specs in 209.719 seconds[0m
    [1m[91mFAIL![0m -- [32m[1m2 Passed[0m | [91m[1m3 Failed[0m | [33m[1m0 Pending[0m | [36m[1m0 Skipped[0m --- FAIL: TestApplications (209.72 seconds)
    FAIL

**Comment by Amit-PivotalLabs** [comment]
This should be fixed by: https://github.com/cloudfoundry/cf-acceptance-tests/commit/06c83fa5641785ebca1c6dedb36c2370415e3005.
