### ISSUE TITLE
Cf ssh-ing broken with certain commands 

### ISSUE THREAD

**Issue by ameowlia** [cloudfoundry/cf-acceptance-tests#266]
In my cats test I wanted to ssh into an app and curl a url. If I do this outside of cats, it looks like this: 
```
$ cf ssh proxy -c "curl https://google.com"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>301 Moved</TITLE></HEAD><BODY>
<H1>301 Moved</H1>
The document has moved
<A HREF="https://www.google.com/">here</A>.
</BODY></HTML>
100   220  100   220    0     0   3676      0 --:--:-- --:--:-- --:--:--  3793
```

When I run it in cats, the code looked like this: 
```
cmd := "\"curl  https://google.com\""
envCmd := cf.Cf("ssh", "-v", appName, "-c", cmd)
```

The cats output looks reasonable: 
```
cf ssh -v CATS-1-APP-fc3d92352444f038 -c "curl https://google.com"
```

But then I get an error:
```
/bin/bash: curl https://google.com: command not found
```

If I prevent cats from cleaning up and I run this code from the CLI on the exact same app, it works. 

Experiments I've tried:

I was wondering if the issue was that the command has multiple arguments in it. If the command is `dig` instead of `curl` it fails similarly. If the command is `echo`, it works.

**Comment by dsabeti** [comment]
Hi @ameowlia. I saw that you submitted [this PR](https://github.com/cloudfoundry/cf-acceptance-tests/pull/268) after opening this issue. Do you still need help with this?

**Comment by ameowlia** [comment]
Hi @dsabeti, 

With the PR, this is no longer a blocking issue, however, it is still broken. 

Thanks, 
@ameowlia

**Comment by dsabeti** [comment]
Ok, thanks. I've prioritized this issue as a story so the engineering team can look into understanding and fixing the issue.

**Comment by ishustava** [comment]
Hey @ameowlia,

Looking at the code, it looks like `cf.Cf` is just a wrapper of the `golang`'s `exec.Command` function, and it already "stringifies" command args correctly. Meaning, if you drop the escaped quotes, it should work. I've pushed an example to a branch [here](https://github.com/cloudfoundry/cf-acceptance-tests/blob/7f5b6fc9bde128df65ebdf39f420e8ec5b8c337f/ssh/ssh.go#L104-L111).

The ssh package already has [a similar test](https://github.com/cloudfoundry/cf-acceptance-tests/blob/10e32db7f38c4b685667f2cfeeb1dce7a4da7dd1/ssh/ssh.go#L88), so I think there is no need for us to add more.

Let us know if that works for you.

Thanks!

**Comment by dsabeti** [comment]
Hey @ameowlia, have you had a chance to try Iryna's suggestion?

**Comment by ameowlia** [comment]
@dsabeti I recall trying that when I was initially work on  the story, but it didn't work in our pipeline (strangely, I think it did work in CAPIs). We switched to using our proxy app in our CAT that gives us the info we need when we ping an endpoint so we never have to ssh in anymore.

**Comment by dsabeti** [comment]
Sounds good. Thanks!
