### ISSUE TITLE
Escape special characters

### ISSUE THREAD

**Issue by norshtein** [cloudfoundry/cf-acceptance-tests#275]
I deployed cloud foundry on Azure and I used application gateway(layer 7 load balancing) to distribute traffic.When I run CATs,I got the following error:

```
• Failure [38.235 seconds]
[apps]
/go/src/github.com/cloudfoundry/cf-acceptance-tests/cats_suite_helpers/cats_suite_helpers.go:39
  Routing Transparency
  /go/src/github.com/cloudfoundry/cf-acceptance-tests/cats_suite_helpers/cats_suite_helpers.go:38
    transparently proxies both reserved characters and unsafe characters [It]
    /go/src/github.com/cloudfoundry/cf-acceptance-tests/apps/routing_transparency.go:57

    Expected
        <string>: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">
        <HTML><HEAD><TITLE>Bad Request</TITLE>
        <META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD>
        <BODY><h2>Bad Request - Invalid URL</h2>
        <hr><p>HTTP Error 400. The request URL is invalid.</p>
        </BODY></HTML>
        
    to contain substring
        <string>: /requesturi/!~^'()$"

    /go/src/github.com/cloudfoundry/cf-acceptance-tests/apps/routing_transparency.go:55
```

I checked `routing_transparency.go` and manually deployed the same app(assets/golang/site.go) to cloud foundry.When I visited `http://gosite.mydomain/requesturi/!~^'()$"?!'()$#!'` using chrome,it seems working correctly and I got the following page:
```
Request URI is [/requesturi/!~%5E'()$%22?!%27()$]
Query String is [!%27()$]
```
I opened the developer tool and found the browser will escape special characters automatically.But when I used curl command: `curl 'http://gosite.mydomain/requesturi/!~^'  "'"  '()$"?!'  "'"  '()$#!'  "'"`(I have separated nested quotes for human reading,there is no space in my initial command),I got the following page as I got when running CATs:
```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">
<HTML><HEAD><TITLE>Bad Request</TITLE>
<META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD>
<BODY><h2>Bad Request - Invalid URL</h2>
<hr><p>HTTP Error 400. The request URL is invalid.</p>
</BODY></HTML>

```
I escaped double quotes manually and run the command again: `curl 'http://gosite.mydomain/requesturi/!~^'  "'"  '()$%22?!'  "'"  '()$#!'  "'"`,this time I got desired output:
```
Request URI is [/requesturi/!~%5E'()$%22?!'()$]
Query String is [!'()$]
```
It seems that the application gateway in Azure cannot deal with unescaped double quote in URL as desired.When using chrome,chrome will escape special character automatically so the application gateway can work correctly,but when using curl , curl won't escape special character so the application gateway returned error 400.
I'm wondering is this test case is designed deliberately to test whether cf can work properly with unescaped special characters in URL? If not, could you escape double quote in this test case?

**Comment by dsabeti** [comment]
Hey @norshtein, it took me a minute to dig up the history of this test. The initial commit (https://github.com/cloudfoundry/cf-acceptance-tests/commit/6d7f6929b2e7692ef98e351311c11cde499d177d) suggests that the test was added to make sure that the gorouter didn't attempt to change the encoding of any requests being made to apps. There's also another test in that same file that validates that escaped characters are properly passed on to the application.

My sense is that we need to keep these characters unescaped. Given that there's a test case that tests the other scenario with escaped characters, validating the requests can go transparently through the router with unescaped characters seems valuable.

Still, I'm going to loop in in @shalako, @shubhaat, and @aaronshurley from the Routing team (who maintain the gorouter) and see if they have any context on this functionality. I wonder if it's also worth getting help from the folks him maintain the Azure integration to see if this is something we should expect from the Azure load balancers.

**Comment by norshtein** [comment]
Hi @dsabeti ,thanks for your patient responding. I think there is no problem with go router.I have logged into the router in the cluster and investigated the running log of the router.There is no routing record having unescaped characters in URL, and escaped URL is recorded correctly.It seems that the application gateway(7 layer load balancer in Azure) took over the http request , and the application gateway returned 400 bad request when there exists unescaped character in URL ,then this http request is discarded and won't be delivered to the router.
Then I tried to use load balancer(4 layer load balancer in Azure). Since load balancer won't take over http request,it will only route the request to the router, everything was ok and I passed CATs.
We will contact Azure application gateway team and ask for their help.

**Comment by dsabeti** [comment]
Hi @norshtein, I'm going to go ahead and close the issue, since the problem seems to be more with the Azure load balancer than with CF or CATs. But feel free to re-open if you think there's more to discuss here.

**Comment by bingosummer** [comment]
Hi @dsabeti , according to [rfc1738.txt](http://www.ietf.org/rfc/rfc1738.txt), `all unsafe characters must always be encoded within a URL.`
So, the case `transparently proxies both reserved characters and unsafe characters` may be invalid ?

**Comment by bingosummer** [comment]
Thanks @dsabeti for your response and detail explanation. Appreciated your help.
I'll open a Github issue in routing-release to discuss more.

**Comment by norshtein** [comment]
Hi @bingosummer , the test can be passed by setting "SKIP_REGEXP" parameter in [run-cats](https://github.com/cloudfoundry/cf-deployment-concourse-tasks/blob/master/run-cats/task.yml#L31) concourse task. In this case, we can set `SKIP_REGEXP: "transparently proxies both reserved characters and unsafe characters"`.
