### ISSUE TITLE
include_container_networking not respected in include_tasks

### ISSUE THREAD

**Issue by andrew-edgar** [cloudfoundry/cf-acceptance-tests#286]
We have not installed C2C but did want to test tasks.  A new test in the tasks 2 "requires" C2C.

This should not be the case that this test is included when I have include_container_networking false.

We need a better way to turn on and off tests.  But at this point I now cannot test "tasks" without C2C.  This seems incorrect.

**Comment by dsabeti** [comment]
Hey @andrew-edgar, thanks for pointing this out. I haven't accepted the story yet to add this test in the first place, so it looks like I should reject it with this feedback. I'll update this issue once we've fixed it.

cc @heyjcollins

**Comment by dsabeti** [comment]
And here's the story if you're interested in following along: https://www.pivotaltracker.com/story/show/156293927

**Comment by dsabeti** [comment]
Hi @andrew-edgar. Is this issue still happening?

**Comment by cdutra** [comment]
Hi @andrew-edgar,
We're going to close this issue because it seems the issue has been fixed. Feel free to reopen if this it's still an issue. Thanks
cc @davewalter
