### ISSUE TITLE
`unallocated_ip_for_security_group` is not referenced in README

### ISSUE THREAD

**Issue by kkallday** [cloudfoundry/cf-acceptance-tests#289]
Hi all,

Our team has began testing with the windows suite turned on. There is a integration config param called `unallocated_ip_for_security_group` that is not referenced in the README. It would be nice to have an explanation on what this is used for, its default value, and why you might need to override it.

I believe folks from the windows team (garden-windows specifically) would have the most context.

cc @aminjam @sesmith177 @ankeesler

Thanks!

**Comment by kkallday** [comment]
Also seems like the 'include_security_groups' arg to integration config isn't being respected by tests in the windows suite. See message at the end of this line: https://github.com/cloudfoundry/cf-acceptance-tests/blob/9f031a6b2d8d8ddfc1245cc1c19db697dd0b9501/windows/running_security_groups_win.go#L135

**Comment by njbennett** [comment]
Hey @kkallday , can you open another issue for the "`include_security_groups` isn't being respected" issue?

**Comment by kkallday** [comment]
@njbennett sure, see #297
