### ISSUE TITLE
The "emits crash events and reports as 'crashed' after enough crashes" is flaky with newer versions of cf-cli

### ISSUE THREAD

**Issue by ljfranklin** [cloudfoundry/cf-acceptance-tests#293]
[This test](https://github.com/cloudfoundry/cf-acceptance-tests/blob/ae2c8d23a3dc338cb5150fae0f4305d070d12920/apps/crashing.go#L50) expects `cf start` to exit non-zero when given a bogus command like `/bin/false`. However, we just saw the test fail as `cf start` exited 0 with the following output:

```
Waiting for app to start...

name:              CATS-4-APP-0e015841db2801b7
requested state:   started
instances:         1/1
usage:             256M x 1 instances
routes:            cats-4-app-0e015841db2801b7.apps.hickory-rabbit.gcp.releng.cf-app.com
last uploaded:     Sat 21 Apr 04:03:07 UTC 2018
stack:             cflinuxfs2
buildpack:         binary_buildpack
start command:     /bin/false

     state      since                  cpu    memory      disk      details
#0   starting   2018-04-21T04:03:21Z   0.0%   0 of 256M   0 of 1G 
```

According to the [CLI team](https://cloudfoundry.slack.com/archives/C032824SM/p1524595217000468), `cf start` is not guaranteed to wait until the command crashes and may report back `starting` as seen above. Could this test be rewritten to check that eventually the state changes to `crashed`?

**Comment by heyjcollins** [comment]
Hey @ljfranklin ,
Thanks for bringing this to our attention.
We don't see this failure as I recall.
Anything fancy/unique about your CF we should know about?
That would help us dig in a bit. 
Also, how frequently are you seeing this flake out?

**Comment by ljfranklin** [comment]
@heyjcollins we saw this failure twice yesterday, I'm not sure whether it occurred before that. I'm not sure why we starting seeing it, but the CLI team indicated that the CLI is not required to waiting until the state changes to `crashed` before returning from `cf start`: https://cloudfoundry.slack.com/archives/C032824SM/p1524595217000468. So at minimum the test is relying on behavior from the CLI that is not guaranteed.

**Comment by heyjcollins** [comment]
@ljfranklin - I'll follow up with the teams here and consider the alternatives and get back to you. In the meantime, could you describe your CF set up? Thanks!

**Comment by Syerram** [comment]
@ljfranklin Is this still an open issue? We have not seen this test fail in our pipelines. Closing for now but please reopen if you're still seeing this issue.
