### ISSUE TITLE
Windows lifecycle test has a short timeout

### ISSUE THREAD

**Issue by ljfranklin** [cloudfoundry/cf-acceptance-tests#301]
We're occasionally seeing the following test failure in our env:

```
• Failure [20.711 seconds]
[windows] Task Lifecycle [It] exercises the task lifecycle on windows 
/tmp/build/33ac16d1/go/src/github.com/cloudfoundry/cf-acceptance-tests/windows/tasks.go:44

  Timed out after 1.000s.
  Expected process to exit.  It did not.

  /tmp/build/33ac16d1/go/src/github.com/cloudfoundry/cf-acceptance-tests/windows/tasks.go:46
```

Looks like this line isn't using the `DefaultTimeoutDuration`: https://github.com/cloudfoundry/cf-acceptance-tests/blob/bce1d3d3209c4bdc8317bcc1963dea8f67976e3b/windows/tasks.go#L46.

Instead of adding timeout to lines one at a time, have y'all considered setting the global default timeout? http://onsi.github.io/gomega/#modifying-default-intervals

**Comment by heyjcollins** [comment]
Hey @ljfranklin -- Thanks for bringing this up. It seems like a reasonable thing to address. We'll pull this in as a story in our backlog.

**Comment by ishustava** [comment]
Hey @ljfranklin,

We have recently [added default eventually timeout and polling interval](https://github.com/cloudfoundry/cf-acceptance-tests/commit/bdbf3cdd3e64ce3af6b8165e8659c26fa99baa65), so we expect this problem to go away. I ran this test with `-untilItFails` flag, and it succeeded 16 times in a row.  

I'll go ahead and close this issue for now, but please feel free to open another one if you see issues again.
