### ISSUE TITLE
Loggregator performance can cause intermittent test failure

### ISSUE THREAD

**Issue by henrytk** [cloudfoundry/cf-acceptance-tests#308]
## The problem

We are seeing intermittent failure of the ["It applies default environment variables while staging apps"](https://github.com/cloudfoundry/cf-acceptance-tests/blob/cf1.38/apps/default_environment_variables.go#L81-L112) test. It expects to see an environment variable in the output and does not.

```
applies default environment variables while staging apps [It]

      Expected
          <string>:    2018-06-19T12:16:57.60+0000 [API/1] OUT Created app with guid bc615398-a76f-4736-bebe-d3948655060f
      to match regular expression
          <string>: LANG=en_US\.UTF-8
```

## The cause

We have concluded these failures are due to assertions being made on the output of `cf logs|tail` before the logs have made it through Loggregator.

## A solution

We believe assumptions shouldn't be made about the performance of Loggregator. To assume logs can make it through Loggregator in the time it takes to run `cf logs|tail` will lead to intermittent failures when performance (throughput) drops for any reason.

Would you consider making the assertions in such tests use `Eventually`? This would allow a configurable amount of time for the logs to make it through and reduce the noise of flaky failing tests.

**Comment by tlwr** [comment]
I just wanted to bump this, we are still experiencing this even with Ginkgo `flake` set to `3`, even with the change from `cf logs` to `cf tail`. Would you accept a PR from us to fix this?

Thanks

**Comment by davewalter** [comment]
Hi @tlwr,

Sorry for the extremely delayed response. We checked our failure logs and can't find any evidence of that test failing for us recently. That having been said, I think a block such as the one [here](https://github.com/cloudfoundry/cf-acceptance-tests/blob/cf1.38/apps/default_environment_variables.go#L156-L163) would go a long way to making the test less flaky for you. We would welcome such a PR if you have the bandwidth to make the change.

Regards,
Dave and @Changdrew

**Comment by tlwr** [comment]
We are still seeing these problems but I will wait until after cf-deployment release 10 to resume investigation.

**Comment by Syerram** [comment]
@tlwr cf-deployment v11 is released. Please reopen this issue if the problem persists.
