### ISSUE TITLE
Some errors in helpers are silently ignored

### ISSUE THREAD

**Issue by ljfranklin** [cloudfoundry/cf-acceptance-tests#322]
Just a heads up, when we load CATs in VIM our linter sees a lot of "error return value not checked" linting errors, e.g. [here](https://github.com/cloudfoundry/cf-acceptance-tests/blob/3ae9bc8c6737c063f9b6779ad845d39b582dbdf2/helpers/v3_helpers/v3.go#L36). This could result in hard to debug failures where an earlier failure results in a nil pointer or empty string while the original error is dropped.

**Comment by davewalter** [comment]
Thanks for bringing this to our attention @ljfranklin. We are currently working on improving CATs debug-ability so we will definitely keep this in mind as we review the code.

Regards,
Dave and @weymanf
