### ISSUE TITLE
dynamic_info test is redundant

### ISSUE THREAD

**Issue by jenspinney** [cloudfoundry/cf-acceptance-tests#368]
Hi!

We noticed that a test in `apps/dynamic_info.go` seems to be duplicating coverage with other tests in the apps suite.

https://github.com/cloudfoundry/cf-acceptance-tests/blob/5550ae6462f849142a341f7f8e2bd2ba6571943f/apps/dynamic_info.go#L38-L49 

It looks like this behavior is covered by the tests in crashing.go:
https://github.com/cloudfoundry/cf-acceptance-tests/blob/5550ae6462f849142a341f7f8e2bd2ba6571943f/apps/crashing.go#L49-L78 

Can the "shows crash events and recovers from crashes" test be removed from dynamic_info.go?

**Comment by davewalter** [comment]
Thanks for pointing this out @jenspinney. We've deleted the duplicate test in https://github.com/cloudfoundry/cf-acceptance-tests/commit/ed4d2f4859a9cf0ddb35b226e38157fc3b6aaed7.
