### ISSUE TITLE
how to make the default running security groups block access

### ISSUE THREAD

**Issue by nkuacac** [cloudfoundry/cf-acceptance-tests#39]
Hi.
I run the test SecurityGroups fail.Maybe it is because of the cloud foundry is not config default security groups. 
Is there a security groups configuration document of Cloud foundry? I'm not sure that the security groups of Cloud foundry is the same as security groups of Openstack.

Thanks.

**Comment by ShwethaKumbla** [comment]
hi @jfmyers9 @zrob  @stupakov 
 
Is this issue is resolved?

I still face the issue when i am behind the proxy.

After setting the http_proxy env for the apps as below test case is passing.

```
	config := helpers.LoadConfig()
		http_proxy := config.HttpProxy
		https_proxy := config.HttpsProxy
		if "" != http_proxy {
			Expect(cf.Cf("set-env", testAppName, "http_proxy", http_proxy).Wait(DEFAULT_TIMEOUT)).To(Exit(0))
			Expect(cf.Cf("set-env", testAppName, "https_proxy", https_proxy).Wait(DEFAULT_TIMEOUT)).To(Exit(0))
		}
```

We need to configure the http_proxy env for apps to pass this test case.

Thanks
@ShwethaKumbla
