### ISSUE TITLE
How to fix /apps/loggregator.go "reverse log proxy" spec failure?

### ISSUE THREAD

**Issue by gu-bin** [cloudfoundry/cf-acceptance-tests#403]
Would you please advise how to fix this CF CATs failure?
```
------------------------------
• Failure [125.076 seconds]
[apps]
/gopath/src/github.com/cloudfoundry/cf-acceptance-tests/cats_suite_helpers/cats_suite_helpers.go:32
  loggregator
  /gopath/src/github.com/cloudfoundry/cf-acceptance-tests/cats_suite_helpers/cats_suite_helpers.go:38
    reverse log proxy
    /gopath/src/github.com/cloudfoundry/cf-acceptance-tests/apps/loggregator.go:129
      streams logs [It]
      /gopath/src/github.com/cloudfoundry/cf-acceptance-tests/apps/loggregator.go:130
      Timed out after 60.038s.
      To enable the log-stream feature, please ask your CF administrator to enable the RLP Gateway and to add the 'doppler.firehose' scope to your CF admin user.
      Expected
          <string>: 
      to contain substring
          <string>: Muahaha
      /gopath/src/github.com/cloudfoundry/cf-acceptance-tests/apps/loggregator.go:160
------------------------------
```
I’ve checked that the CF admin user has the ‘doppler.firehose’ scope. How to check if RLP Gateway is enabled? Thanks.

**Comment by davewalter** [comment]
Hi @gu-bin,

From what we can tell, it should be enabled by default in the base cf-deployment.yml manifest [here](https://github.com/cloudfoundry/cf-deployment/blob/86a598389c5a32d14c177d36b1d005f850f38d4b/cf-deployment.yml#L1616-L1642). If you run `bosh is --ps`, do you see the `reverse_log_proxy_gateway` process running on the log-api instance(s)?

Regards,
Dave and Sebastian (@vitreuz)

**Comment by gu-bin** [comment]
Yes, the process `reverse_log_proxy_gateway` is running on log-api. So RLP Gateway is enabled. Anything else do we need to check?

**Comment by pivotaljohn** [comment]
Without knowing the details of your setup, it's hard to say.

Given that is appears related to logging setup, you might be able to get some traction with the Loggregator team: [#loggregator](https://cloudfoundry.slack.com/archives/C02HCCXV5).
