### ISSUE TITLE
Move cloudfoundry/diego-docker-app-custom to RelInt CI

### ISSUE THREAD

**Issue by sunjayBhatia** [cloudfoundry/cf-acceptance-tests#411]
Diego recently received [a PR to update the `cloudfoundry/diego-docker-app-custom` Docker image](https://github.com/cloudfoundry/diego-dockerfiles/pull/5). While reviewing, we realized this image is not used anywhere in Diego CI but only in CATs as a default image to use in some Docker-related tests (see [here](https://github.com/cloudfoundry/cf-acceptance-tests/blob/d51a1d65d7242bc5a6dfb7bd87b259f76a6c545a/helpers/config/config_struct.go#L228) and the [`README.md`](https://github.com/cloudfoundry/cf-acceptance-tests#private-docker)).

Can we move this image to be owned by the RelInt team as it is only a CATs dependency? It feels risky and disorganized for this image to continue to be owned by Diego (there's nothing keeping us from accidentally changing/deleting it and it makes more sense to keep the dependencies all in one place with one owner).

**Comment by jpalermo** [comment]
We updated CATS to use diego-docker-app instead of diego-docker-app-custom.

I'd like to say that you can just delete the docker image now, but all the existing versions of cf-acceptance-tests will still try to pull from it and that would cause breakage. You can probably delete the file from the `diego-dockerfiles` repo though and just orphan the image in it's current state.

**Comment by sunjayBhatia** [comment]
cc @cloudfoundry/cf-diego

**Comment by aminjam** [comment]
@jpalermo the [`diego-docker-app`](https://hub.docker.com/r/cloudfoundry/diego-docker-app) image you referred to above is still maintained by the diego team and could still potentially break the CATS. Are you referring to a different image that's maintained by the relint or the same image?

**Comment by jpalermo** [comment]
@aminjam, yeah, we are still using one maintained by the diego team. We realize this may lead to breakages of CATs, but that seems preferable for now at least.

If the breakages become too frequent we can evaluate forking the docker app and maintaining a copy in cf-acceptance-tests directly.

**Comment by sunjayBhatia** [comment]
@jpalermo if youre ok with it, sounds fine; that image is unlikely to change much and is part of some of our integration test suites but we figured we would warn you
