### ISSUE TITLE
Inconsistent vendoring in v5.9.0

### ISSUE THREAD

**Issue by georgethebeatle** [cloudfoundry/cf-acceptance-tests#413]
Hi,

We in @cloudfoundry/eirini bumped the cf-acceptance-tests from v5.8.0 to v5.9.0 and started seeing the following error message when running them with `bin/test`:
```
go: inconsistent vendoring in /home/vagrant/workspace/cf-acceptance-tests:
        golang.org/x/crypto@v0.0.0-20200323165209-0ec3e9974c59: is explicitly required in go.mod, but vendor/modules.txt indicates golang.org/x/crypto@v0.0.0-20190820162420-60c769a6c5
86

run 'go mod vendor' to sync, or use -mod=mod or -mod=readonly to ignore the vendor directory
```

When we run `go mod vendor` the error is gone. Could you please fix this?

**Comment by ericpromislow** [comment]
This was fixed on Apr 23 in commit 670a9c3
and available in CATS [v5.10.0](https://github.com/cloudfoundry/cf-acceptance-tests/releases/tag/v5.10.0)

@ericpromislow and @jamespollard8
