### ISSUE TITLE
Ginkgo 2.0 Proposal

### ISSUE THREAD

**Issue by onsi** [cloudfoundry/cf-acceptance-tests#427]
Hi all!

I'm working on a proposal for Ginkgo 2.0.  I'll be sharing a more public version soon but wanted to give folks maintaining complex test suites early access to the doc to get a first round of feedback.  Please let me know if anyone would be interested in getting access to the doc!

**Comment by paulcwarren** [comment]
I would love to see that @onsi

**Comment by acosta11** [comment]
For team visibility: the proposal link is available in https://github.com/onsi/ginkgo/issues/711

**Comment by jamespollard8** [comment]
Thanks Onsi!

We've had several teammates review the proposal. I'll share some comments that @ericpromislow dropped on our story and I'll close out this issue.

>This is more of a non-issue; the actual issue will be to migrate CATs to ginkgo 2.0. However, we can make this a team task to read the proposal document. Check your name off in the task list once you've done that. When all the tasks are done we can close this.

> CATs isn't using any async tests as described in "Deletion: Async Testing Functionality"
> 
> I personally have never used ginkgo for benchmarking
> ("Deletion: Measure Functionality").
> 
> There's a proposal to remove ginkgo convert, which can update the tests from XUnit style to ginkgo. This won't impact us.
> 
> I've never used ginkgo -notify
> 
> The proposed changes look great.
