### ISSUE TITLE
Validate cf version

### ISSUE THREAD

**Issue by fhanik** [cloudfoundry/cf-acceptance-tests#45]
It would be helpful if CATS validated the 'cf' version prior to running all the tests. When the incorrect version of cf is installed, it is very difficult to trace that down.

**Comment by Amit-PivotalLabs** [comment]
This is now done [here](https://github.com/cloudfoundry/cf-acceptance-tests/blob/master/cf_acceptance_test.go#L17-L23).  Closing.
