### ISSUE TITLE
CF acceptance test and KubeCF acceptance test

### ISSUE THREAD

**Issue by mevinod** [cloudfoundry/cf-acceptance-tests#472]
I am quite new to the cloudfoundry as well as to Kubernetes. As I understand - in my project, team is deploying KubeCF using helm charts. So, while filling values.yml in kubecf - we give acceptance test true. I just want to understand if Cloudfoundry acceptance test is same as KubeCF acceptance test.

**Comment by davewalter** [comment]
Hi @mevinod,

From my limited knowledge of KubeCF, I believe that it is the same set of tests, but I would confirm that with the KubeCF team.

Regards,
Dave

**Comment by davewalter** [comment]
Hi @mevinod,

I am going to go ahead and close this issue. Please feel free to reopen it if required.

Regards,
Dave
