### ISSUE TITLE
Branch for `cf17.0`?

### ISSUE THREAD

**Issue by risicle** [cloudfoundry/cf-acceptance-tests#485]
Hi,

Is there expected to be a branch created to correspond to the latest `cf-deployment` `17.0.0` release, presumably `cf17.0`?

**Comment by risicle** [comment]
This seems to exist now. Thanks to whoever added it.

**Comment by davewalter** [comment]
Hi @risicle,

Thanks for pointing this out. The branches are managed automatically by CI once the [CATs pipeline](https://release-integration.ci.cf-app.com/teams/main/pipelines/cats) passes. I hadn't noticed that a build had failed (due to a flake) and needed to be re-triggered.
