### ISSUE TITLE
should the currentCliVersion be increased to 7.1.0?

### ISSUE THREAD

**Issue by metskem** [cloudfoundry/cf-acceptance-tests#491]
There are a few tests that use the cf push **--endpoint** option see [helpers/services/broker.go](https://github.com/cloudfoundry/cf-acceptance-tests/blob/develop/helpers/services/broker.go#L122) , [windows/http_healthcheck.go](https://github.com/cloudfoundry/cf-acceptance-tests/blob/develop/windows/http_healthcheck.go#L39). 
This --endpoint option requires cf cli version 7 or higher.

Should the currentMinCliVersion (now 6.33.1) be increased?

**Comment by jochenehret** [comment]
Yes I guess it makes sense to update the version to >= 7.0.0
https://github.com/cloudfoundry/cf-acceptance-tests/blob/6f7da9a52562ca93167f3e0e41dea4e79876883f/cats_suite_test.go#L50

**Comment by ctlong** [comment]
`minCliVersion` was bumped to `8.5.0` in #582.
