### ISSUE TITLE
Flake in Apps Streaming Staging Log retrieval

### ISSUE THREAD

**Issue by markstokan** [cloudfoundry/cf-acceptance-tests#545]
It appears with the move to CF7 and logcache, there is no longer a guarantee of staging log delivery during cf push.

https://github.com/cloudfoundry/cf-acceptance-tests/blob/develop/apps/staging_log.go#L34

This is causing flakes in our vSphere/nimbus deployments that aren't as performant.

```
Summarizing 3 Failures:

[Fail] [apps] An application being staged [It] has its staging log streamed during a push 
/__w/tas/tas/.test/cats/apps/staging_log.go:48

[Fail] [apps] An application being staged [It] has its staging log streamed during a push 
/__w/tas/tas/.test/cats/apps/staging_log.go:48

[Fail] [apps] An application being staged [It] has its staging log streamed during a push 
/__w/tas/tas/.test/cats/apps/staging_log.go:48
```

We can retrieve the staging logs after the push with cf logs, we just need more time.

This issue is similar to the one reported [here](https://github.com/cloudfoundry/cf-acceptance-tests/issues/475) and fixed [here ](https://github.com/cloudfoundry/cf-acceptance-tests/pull/505).

Slack thread: https://vmware.slack.com/archives/C3LV25ZCM/p1627378425214800

**Comment by ctlong** [comment]
@markstokan is this still an issue or was it resolved with #505?
