### ISSUE TITLE
CATS fail on SSO Lifecycle tests when CF API v2 is disabled

### ISSUE THREAD

**Issue by stephanme** [cloudfoundry/cf-acceptance-tests#565]
CATS fail when `disable-v2-api` ops file is included:

Example: https://release-integration.ci.cf-app.com/teams/main/pipelines/cf-deployment/jobs/experimental-cats/builds/2435
```
Summarizing 4 Failures:

[Fail] [services] SSO Lifecycle When a service broker is created with a dashboard client [It] can perform an operation on a user's behalf using sso 
/go/src/github.com/cloudfoundry/cf-acceptance-tests/services/sso_lifecycle.go:80

[Fail] [services] SSO Lifecycle When a service broker is updated with a new dashboard client [It] can perform an operation on a user's behalf using sso 
/go/src/github.com/cloudfoundry/cf-acceptance-tests/services/sso_lifecycle.go:116

[Fail] [services] SSO Lifecycle When a service broker is created with a dashboard client [It] can perform an operation on a user's behalf using sso 
/go/src/github.com/cloudfoundry/cf-acceptance-tests/services/sso_lifecycle.go:80

[Fail] [services] SSO Lifecycle When a service broker is updated with a new dashboard client [It] can perform an operation on a user's behalf using sso 
/go/src/github.com/cloudfoundry/cf-acceptance-tests/services/sso_lifecycle.go:116

Ran 165 of 228 Specs in 1704.374 seconds
FAIL! -- 163 Passed | 2 Failed | 0 Flaked | 3 Pending | 60 Skipped
```

RC seems to be https://github.com/cloudfoundry/cf-acceptance-tests/blob/develop/helpers/services/sso.go#L154 which contains a hardcoded CF API v2 endpoint: /v2/service_instances/:guid/permissions

There is no direct replacement for this endpoint in CF API v3 (maybe /v3/roles).

**Comment by stephanme** [comment]
WIP:
- https://github.com/cloudfoundry/cloud_controller_ng/issues/2872
- https://github.com/cloudfoundry/cloud_controller_ng/pull/2880

**Comment by jochenehret** [comment]
Issue has been fixed. The "experimental" environment runs with disabled v2 API:
https://github.com/cloudfoundry/cf-deployment/blob/04da087800ce57b123c92e4862b3161219af67ce/ci/pipelines/cf-deployment.yml#L1203
Closing this issue.
