### ISSUE TITLE
Automation to vendir dependencies

### ISSUE THREAD

**Issue by ctlong** [cloudfoundry/cf-acceptance-tests#573]
`assets/logging-route-service` is included via vendir. However, we don't have automation to sync the directory on occasion. We should set this up so that we're staying up-to-date with any changes to that repo.

**Comment by jochenehret** [comment]
We have a Dependabot job now for updating the asset:
https://github.com/cloudfoundry/cf-acceptance-tests/blob/main/assets/logging-route-service/.github/dependabot.yml
vendir was removed quite some time ago.
