### ISSUE TITLE
Config option to point to a different CF binary.

### ISSUE THREAD

**Issue by squeedee** [cloudfoundry/cf-acceptance-tests#64]
This would simplify test setup. What I like about the config.json is that it's one decalarative place to describe all the external dependencies. That way if a cats fails in CI, i can grab the config and try again locally.

**Comment by jpalermo** [comment]
@squeedee 

That seems like a reasonable feature. We gave it a quick try and quickly ran into go import cycle problems when trying to access the `config` object from inside of the `cf` runner.

But if you wanted to make a pull request, we'd be happy to merge it.

Joseph & Dies
OSS Release Integration Team

**Comment by zaksoup** [comment]
There hasn't been any movement on this so I'm going to close the issue. @squeedee please feel free to submit a PR for this, we'd be love to merge that in.
