### ISSUE TITLE
The `assets/binary` app should not expect Ruby to be available

### ISSUE THREAD

**Issue by ryanmoran** [cloudfoundry/cf-acceptance-tests#809]
The [app that CATS uses](https://github.com/cloudfoundry/cf-acceptance-tests/blob/af5ab9b193db43c330ac52fb69cca51b802b8037/assets/binary/app) to assert the correct functioning of the Binary buildpack is written in Ruby. The assumption in this app is that Ruby is available from the stack somehow. This was true in `cflinuxfs3`, but is no longer the case for `cflinuxfs4`. This application should be re-written so that it does not rely upon the presence of the Ruby runtime in the stack image.

**Comment by arjun024** [comment]
This is fixed by https://github.com/cloudfoundry/cf-acceptance-tests/pull/818
