### ISSUE TITLE
Remove cf-for-k8s things

### ISSUE THREAD

**Issue by ctlong** [cloudfoundry/cf-acceptance-tests#892]
k8s code in cloud_controller_ng was [recently removed](https://github.com/cloudfoundry/cloud_controller_ng/pull/3140), and it seems like cf-for-k8s is properly deprecated now. I think this means we can remove the cf-for-k8s things in this repo.

**Comment by ctlong** [comment]
@davewalter does Korifi use CATs?

**Comment by davewalter** [comment]
No, we have our own end-to-end tests.
