### ISSUE TITLE
no buildpack test for ruby

### ISSUE THREAD

**Issue by landesherr** [cloudfoundry/cf-acceptance-tests#92]
We noticed that the detect suite does not include tests for ruby.

**Comment by Amit-PivotalLabs** [comment]
Let me ask around and see how much of the `detect` suite even makes sense.

**Comment by Amit-PivotalLabs** [comment]
@fraenkel @sykesm @ematpl @jfmyers9 @jvshahid @Dannyzen is this test suite in the CATS even valuable?  The buildpacks pipeline presumably tests all the **detect** behaviour for each buildpack.  There may be something to be said for testing how the platform handles staging when it needs to download lots of things, but that can be tested more intentionally, and perhaps more appropriately at a lower level.

**Comment by fraenkel** [comment]
The reason why it was purposely omitted was because Dora is the defacto test app that is used throughout CATS.  Adding a detect is just a duplicate test. If some other app became the default, then adding a ruby test would be required.

**Comment by Amit-PivotalLabs** [comment]
Yes, but in all other CATS the buildpack is set explicitly, which skips the detect step.

**Comment by fraenkel** [comment]
That was an oversight when someone went through and specified the buildpack everywhere else. Its not how the original tests worked.

**Comment by Amit-PivotalLabs** [comment]
That's true.  Any thoughts on whether this suite still makes sense today?

**Comment by fraenkel** [comment]
At one point all the buildpacks were a required as part of the installation. This is the only set of tests that verify the buildpacks are installed as expected.

**Comment by jvshahid** [comment]
I agree that adding `ruby` buildpack test adds little value, given that the behavior is being tested in other places. That said, i think it is good to have explicit tests as a documention of the buildpacks that are currently supported and shipped with CF. Regarding @Amit-PivotalLabs question, I think we should keep the `buildpack` suite in CATS. My understanding is that users can and should run CATS to verify their deployment is working as expected.

**Comment by Amit-PivotalLabs** [comment]
@fraenkel @jvshahid Thanks.  Would you say then that the value of this suite is not to exercise `detect` logic, but rather to confirm that all the standard buildpacks are working?  I would then propose (a) adding the ruby test here (this suite shouldn't be responsible for knowing that the ruby app is used elsewhere, and is thus safe to omit), and (b) having all the apps explicitly set the buildpack, which one of the tests is actually already doing anyways.

**Comment by fraenkel** [comment]
@Amit-PivotalLabs Umm, no. These sets of tests are very much about detect and making sure that our buildpacks don't conflict. This is now the only place where we do not set the buildpack. With DEAs, one never specified the buildpack. While it should be best practice to set the buildpack, it is not a requirement. Diego went the opposite route because not setting the buildpack made staging a much longer operation. Once bind mounts were added, staging times should have been improved and all those apps not setting the buildpacks should continue to function and not see much of a penalty.

**Comment by Amit-PivotalLabs** [comment]
In order "to have explicit tests as a documention of the buildpacks that are currently supported and shipped with CF" and "making sure that our buildpacks don't conflict" with each other during `detect`, it makes sense to add a ruby test.  @landesherr, were you interested in contributing a PR for this?  If not, that's also cool, the core team can add one.

**Comment by Amit-PivotalLabs** [comment]
@landesherr have not heard back if you wanted to submit a PR, so we will go ahead and add this test.

**Comment by Amit-PivotalLabs** [comment]
Fixed in https://github.com/cloudfoundry/cf-acceptance-tests/commit/b6d4c1a769d107f421ad8a2705dcd264aa345828
