### ISSUE TITLE
The firehose test doesn't test anything

### ISSUE THREAD

**Issue by fraenkel** [cloudfoundry/cf-acceptance-tests#94]
https://github.com/cloudfoundry/cf-acceptance-tests/blob/master/apps/loggregator_test.go#L87

The for loop at line 104 just has us collecting messages for 5 seconds and bailing.

**Comment by wfernandes** [comment]
@fraenkel So we just need to `break` instead of `return` [here](https://github.com/cloudfoundry/cf-acceptance-tests/blob/master/apps/loggregator_test.go#L107)?

**Comment by fraenkel** [comment]
I would hope the test finishes as soon as you see what you are looking for.
This should be an Eventually block.

**Comment by jasonkeene** [comment]
Yes, we agree. We filed a [bug in our backlog](https://www.pivotaltracker.com/story/show/116643815).
