### ISSUE TITLE
Lack of persistence tests to address more serious data loss concerns

### ISSUE THREAD

**Issue by rmasand** [cloudfoundry/cf-acceptance-tests#99]
Hello,

## Issue

The current app persistence tests recreate the app if it doesn't exist, which won't cause a failure if the app disappears during an upgrade.

## Context

We are hoping to offer guidance on performing database migration from postgresql to mysql for existing CF users who want to transfer their data between the 2 databases. We had hoped to use the existing app persistence tests to verify that an app could survive the migration, but realized that those tests are written for a slightly different scenario. The main reason we can't use these is that the test happily pushes the app again if it doesn't exist. We would like a test that would fail if an app (or several apps) are no longer existent after an upgrade. This may also be useful to get feedback on the impact if there is a risky database migration within CCDB or UAADB.

## Expected result

We would like to pass the name of an app to CATs and experience a failure if it does not exist or respond to a restart.

## Current result

When we wipe out the old database and bring up the new one without transferring data, the test recreates the persistent app and there is no failure.

## Possible Fix

A possible fix would involve passing a list of app names, which have already been created out-of-band, after the upgrade. The test would try to locate each one, and perform an action to ensure each app's data has been preserved (a restage or restart would probably work)

Let us know if you need any more context on this issue. @Amit-PivotalLabs I was asked to tag you on this, since it may interest the release-integration team.

Thanks!
Raina Masand and Ryan Moran
PCF Release Engineering

**Comment by Amit-PivotalLabs** [comment]
Spoke with @ryanpei, the testing you're describing is valuable but doesn't belong in CATS.  You will have to manage pushing the app prior to upgrade out-of-band (i.e. in your own script, not part of CATS), and then you would run this hypothetical CAT by passing in configuration with all the credentials, org, space, and app name.  You may as well do this out-of-band too.

There is value in some sort of upgrade stability test suite, which you can have running before, during, and after an upgrade, making valuable assertions throughout.  This is outside the scope of CATS.  The closest thing to this that already exists are the [DUSTS](https://github.com/cloudfoundry-incubator/diego-upgrade-stability-tests), but I don't know how well that test suite generalizes.
